env:
  global:
# CodeClimate.com
    - CC_TEST_REPORTER=858f376754f8ea78678a11d9c302f3a5cf11990e4c9287960869e419733a2bb1

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
# Pypy version:
  - "pypy"
  - "pypy3"

# command to install dependencies
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter --debug before-build

# command to install dependencies
install:
  - pip install -r requirements.txt # install requirements
  - python setup.py install         # install isbg package
  - pip install codecov             # install codecov
  - pip install pytest-cov          # for codecov usage
  - pip install coverage

# command to run tests
script:
  - python setup.py bdist       # create binary distribution
  - python setup.py sdist       # create source distribution
  - pytest --cov-append --cov=isbg tests/   # For codecove usage

after_script:
  - coverage xml                # for codeclimate
  - ./cc-test-reporter after-build --debug --exit-code $TRAVIS_TEST_RESULT

after_success:
  - codecov                     # codecov.io suport
  - isbg --version              # show isbg version

