language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt # install requirements
  - python setup.py install         # install isbg package
  - pip install codecov             # install codecov
  - pip install pytest-cov          # for codecov usage

# command to run tests
script:
  - python setup.py bdist       # create binary distribution
  - python setup.py sdist       # create source distribution
  - pytest --cov-append --cov=isbg tests/   # For codecove usage
  - isbg --version              # show isbg version

after_success:
  - codecov                   # codecov.io suport
